modLoader = "javafml"
loaderVersion = "${neoforge_loader_range}"
license = "${license}"


[[mods]]
    modId = "${mod_id}"
    version = "${version}"
    displayName = "${mod_name}"
    displayURL= "${display_url}"
    logoFile = "${mod_id}.png"
    authors = "${author}"
    description = '''${description}'''

[[dependencies.${mod_id}]]
    modId = "neoforge"
    type="required" #mandatory
    versionRange = "${neoforge_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type="required" #mandatory
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"