modLoader = "javafml"
loaderVersion = "${neoforge_loader_range}"
license = "MIT"


[[mods]]
    modId = "modopedia"
    version = "${version}"
    displayName = "Modopedia"
    displayURL= "https://github.com/Favouriteless/Modopedia"
    logoFile = "modopedia.png"
    authors = "Favouriteless"
    description = '''Data-driven, user-friendly documentation.'''

[[mixins]]
    config="modopedia.neoforge.mixins.json"

[[dependencies.modopedia]]
    modId = "neoforge"
    type="required" #mandatory
    versionRange = "${neoforge_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.modopedia]]
    modId = "minecraft"
    type="required" #mandatory
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"